// <auto-generated />
using System;
using Estudiantes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estudiantes.Migrations
{
    [DbContext(typeof(EstudianteContext))]
    [Migration("20220803231050_addtabla")]
    partial class addtabla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Estudiantes.Models.Calificacione", b =>
                {
                    b.Property<Guid>("IdCal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("IdMath")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdCal")
                        .HasName("PK__Califica__0FA7805667936916");

                    b.HasIndex("IdMath");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Estudiantes.Models.Cuatrimestre", b =>
                {
                    b.Property<Guid?>("IdCuatrimestre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStudentNavigationIdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdCuatrimestre")
                        .HasName("PK__Cuatrimestre");

                    b.HasIndex("IdStudentNavigationIdStudent");

                    b.ToTable("Cuatrimestres");
                });

            modelBuilder.Entity("Estudiantes.Models.Estudiante", b =>
                {
                    b.Property<Guid>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Carrera")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .IsFixedLength();

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdStudent")
                        .HasName("PK__Estudian__61B35104A5E46612");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Estudiantes.Models.Materia", b =>
                {
                    b.Property<Guid>("IdMath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("CuatrimestreIdCuatrimestre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("IdCalificacionesNavigationIdCal")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCuatrimestre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMath")
                        .HasName("PK__Materias__4E66499D56BE1FF2");

                    b.HasIndex("CuatrimestreIdCuatrimestre");

                    b.HasIndex("IdCalificacionesNavigationIdCal");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("Estudiantes.Models.Calificacione", b =>
                {
                    b.HasOne("Estudiantes.Models.Materia", "IdMathNavigation")
                        .WithMany("Calificaciones")
                        .HasForeignKey("IdMath")
                        .HasConstraintName("FK_IdMath");

                    b.Navigation("IdMathNavigation");
                });

            modelBuilder.Entity("Estudiantes.Models.Cuatrimestre", b =>
                {
                    b.HasOne("Estudiantes.Models.Estudiante", "IdStudentNavigation")
                        .WithMany("Cuatrimestres")
                        .HasForeignKey("IdStudentNavigationIdStudent");

                    b.Navigation("IdStudentNavigation");
                });

            modelBuilder.Entity("Estudiantes.Models.Materia", b =>
                {
                    b.HasOne("Estudiantes.Models.Cuatrimestre", null)
                        .WithMany("Materias")
                        .HasForeignKey("CuatrimestreIdCuatrimestre");

                    b.HasOne("Estudiantes.Models.Calificacione", "IdCalificacionesNavigation")
                        .WithMany()
                        .HasForeignKey("IdCalificacionesNavigationIdCal");

                    b.Navigation("IdCalificacionesNavigation");
                });

            modelBuilder.Entity("Estudiantes.Models.Cuatrimestre", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Estudiantes.Models.Estudiante", b =>
                {
                    b.Navigation("Cuatrimestres");
                });

            modelBuilder.Entity("Estudiantes.Models.Materia", b =>
                {
                    b.Navigation("Calificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
